### PR TITLE
Fix Issue #11 - Standup Module

### LINKED ISSUE #11: Standup endpoint
It would be great to encourage more daily standup information. 

- Save (from bot or UI) daily standup information
- Read daily standup information in daily order desc

---

Update after discussion with @mstanciu552 below

> send the information from EddieBot to the API using axios or fetch and then save them in a users collection in our db

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #11 

- [x] Initialize Endpoint for Standups
- [x] Updated Swagger-Documentation

Screen
- [ ] Currently only SearchContext is Discord-Username; This could be extended
- [ ] An Array is used to store date in (like in `discord-service`). This needs to be changed as soon as a Databse is available

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you 👍 . I will review after we merge #49 so we can also add automated tests. Then when we connect a database, the tests should still pass 🤓

File: src/standup/interfaces/Standup.interface.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+export interface IStandup {
```
Comment (eddiejaoude) [inline src/standup/interfaces/Standup.interface.ts:1]: Is this the recommended way to do interface naming in NestJS? From typescript no `I` prepending is needed https://www.typescriptlang.org/docs/handbook/2/objects.html

Comment (Cahllagerfeld) [reply src/standup/interfaces/Standup.interface.ts:1]: To be honest I don't really know.. A colleague at work always did this, so I adapted my style to that.
I could change this if its not necessary.

Comment (eddiejaoude) [reply src/standup/interfaces/Standup.interface.ts:1]: I like to keep things vanilla / recommended from official docs, because it makes it easier to onboard new people. If you could please update 👍

**Comment by Cahllagerfeld** [comment]
Hi @eddiejaoude,

the checks are passing locally at my Computer, I cant really explain why they fail here..
I dont know what that these `fsevents` are..
You have any suggestion what to do?

**Comment by eddiejaoude** [comment]
No problem, I can look into the issues soon.

Btw we also write end-to-end tests, here is an example https://github.com/EddieHubCommunity/api/blob/main/test/features/discord.feature any questions let us know

**Comment by Cahllagerfeld** [comment]
> 
> 
> Hi @eddiejaoude,
> 
> the checks are passing locally at my Computer, I cant really explain why they fail here..
> I dont know what that these `fsevents` are, but they seem to be the reason for failure
> You have any suggestion what to do?

The Problem when passing the checks seems to be while installing the dependencies, not while the actual check itself.

 
> 
> No problem, I can look into the issues soon.
> 
> Btw we also write end-to-end tests, here is an example https://github.com/EddieHubCommunity/api/blob/main/test/features/discord.feature any questions let us know

Sure I'll add some.
I'll probably wont have enough time today to initialize and commit the e2e-Tests today. For this reason I'll suggest leaving this PR open until I updated them.

**Comment by eddiejaoude** [comment]
> The Problem when passing the checks seems to be while installing the dependencies, not while the actual check itself.

it might be a version incompatibility issue. What version of node are you using locally? I can test locally also later on.

> I'll probably wont have enough time today to initialize and commit the e2e-Tests today. For this reason I'll suggest leaving this PR open until I updated them.

No problem, we can leave it open 👍

**Comment by Cahllagerfeld** [comment]
My local Node-Version is `v14.15.4`
Local npm is `7.9.0`

**Comment by Cahllagerfeld** [comment]
Hi @eddiejaoude as discussed on the discord server, we should introduce step-definitions for responses. In this case we need a step-definition for testing the `standup-search`-endpoint. The datastructure is the following: 
```ts 
[
  {
    "id": number,
    "yesterdayMessage": string,
    "todayMessage": string,
    "discordUser": string,
    "createdOn": Date
  }
]
```

You prefer collborating directly in this PR here, or open an issue for that?

**Comment by eddiejaoude** [comment]
Thanks @Cahllagerfeld for the context 👍 

I think we are missing this functionality. 
We need a step definition like this (untested) in file `test/step-definitions/responses.ts` 
```ts
@then(/the response in item "([^"]*)" should contains:/)
public dataResponseItemTable(item: number, table: { rawTable: [] }) {
  const data = this.context.tableToObject(table);
  expect(JSON.parse(this.context.response.text)[item]).to.to.eql(data);
}
```

File: test/features/standup.feature [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+        Then the response status code should be 201
+        And the response should contains:
+            | discordUser      | "eddiehubber"              |
+            | yesterdayMessage | "yesterday I did this"     |
+            | todayMessage     | "Today I'll do this"       |
+            | createdOn        | "2021-01-01T00:00:00.000Z" |
+            | id               | 666                        |
+
+
+    //TODO Step Definition Array of Objects
```
Comment (Cahllagerfeld) [inline test/features/standup.feature:22]: Thats the Test for the Search Endpoint, which returns an Array ob Standup-Objects.

File: test/features/standup.feature [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+    Scenario: search Standup
+        Given make a POST request to "/standup" with:
+            | discordUser      | "eddiehubber"          |
+            | yesterdayMessage | "yesterday I did this" |
+            | todayMessage     | "Today I'll do this"   |
+        Then  make a POST request to "/standup/search" with:
+            | discordUser | "eddiehubber" |
+        Then the response status code should be 201
+        And  the response should be:
```
Comment (eddiejaoude) [inline test/features/standup.feature:31]: Is this missing the return data?

Comment (Cahllagerfeld) [reply test/features/standup.feature:31]: Exactly, I didnt know how to project the Data-Structure described earlier in this PR as a Datatable that cucumber can validate it. Because of that reason I dont have a check for the Response yet

File: test/features/standup.feature [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+
+    Scenario: search Standup
+        Given make a POST request to "/standup" with:
+            | discordUser      | "eddiehubber"          |
+            | yesterdayMessage | "yesterday I did this" |
+            | todayMessage     | "Today I'll do this"   |
+        Then  make a POST request to "/standup/search" with:
+            | discordUser | "eddiehubber" |
+        Then the response status code should be 201
+        And  the response in item "0" should contains:
```
Comment (Cahllagerfeld) [inline test/features/standup.feature:30]: This line uses the new Step-Definition. I am not sure if this is how it is intended to work, but locally it passed the test successfully with this.

**Comment by Cahllagerfeld** [comment]
I reinvestigated the failure of the checks. It seems like it has sth to do with this commit. `c22711238127eff1543510f4038fb2a2dd9ba1c5`. In this Commit about 11000 lines of code get deleted from package-lock. When I delete `package-lock` locally and reinstall dependencies these 11000 lines are getting added back. Maybe - no guarantee - this causes the checks to fail.

**Comment by eddiejaoude** [comment]
Thank you for making the changes 🤓 

I think you might be right, try deleting the lock file and doing an `npm install` and committing the new lock file 👍

I ran the tests locally and they pass 🎉 , I also purposely broke the test to make sure it was testing and it failed correctly (see screenshot below)

This is vey close to be able to merge, thank you 💥 

---

Testing a broken test fails...

Screenshot 2021-04-16 at 09 15 29

File: test/features/standup.feature (hunk 3 above)
Comment (eddiejaoude) [reply test/features/standup.feature]: ok thanks 👍

File: test/features/standup.feature (hunk 4 above)
Comment (eddiejaoude) [reply test/features/standup.feature:30]: ok great 👍

File: test/features/standup.feature [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+            | createdOn        | "2021-01-01T00:00:00.000Z" |
+            | id               | 666                        |
+
+
+    Scenario: search Standup
+        Given make a POST request to "/standup" with:
+            | discordUser      | "eddiehubber"          |
+            | yesterdayMessage | "yesterday I did this" |
+            | todayMessage     | "Today I'll do this"   |
+        Then  make a POST request to "/standup/search" with:
```
Comment (eddiejaoude) [inline test/features/standup.feature:27]: I think `search` should be a `GET` with a query parameter, something like `GET /standup?discordUser=eddiehubber`

Comment (Cahllagerfeld) [reply test/features/standup.feature:27]: I had the same thoughts while coding this. I made it a Post in case the SearchContext is getting more complex in the future so the URL doesnt get too long with too many parameters. 
Do we need more properties be searchable in this context when I adjust this endpoint?

Comment (eddiejaoude) [reply test/features/standup.feature:27]: I think keep it simple for now.

In the future we might want
- keyword search that searches `yesterdayMessage` and `todayMessage`
- date range filter (for example list the last 3 days for all users, or filter by user as well)

Comment (Cahllagerfeld) [reply test/features/standup.feature:27]: Okay I'll implement the simple way for now then! :D

File: src/standup/standup.controller.ts [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+  @Post()
+  createStandup(@Body() body: CreateStandupDTO) {
+    return this.standupService.create(body);
+  }
+
+  @Get()
+  findAllStandups() {
+    return this.standupService.findAll();
+  }
+  @Get('search')
```
Comment (Cahllagerfeld) [inline src/standup/standup.controller.ts:29]: Search is now get

File: test/features/standup.feature [hunk 7]
```diff
@@ -19,21 +19,41 @@ Feature: Standup-module
...
+        Then  make a GET request to "/standup/search?discordUser=eddiehubber"
+        Then the response status code should be 200
         And  the response in item "0" should contains:
             | discordUser      | "eddiehubber"              |
             | yesterdayMessage | "yesterday I did this"     |
             | todayMessage     | "Today I'll do this"       |
             | createdOn        | "2021-01-01T00:00:00.000Z" |
             | id               | 666                        |
 
+    Scenario: search non-existing Standup
```
Comment (Cahllagerfeld) [inline test/features/standup.feature:36]: Added some additional Tests

File: src/standup/standup.controller.ts (hunk 6 above)
Comment (eddiejaoude) [reply src/standup/standup.controller.ts:29]: Great thanks 👍 

Btw I think a blank line is needed between the methods

File: test/features/standup.feature [hunk 8]
```diff
@@ -0,0 +1,85 @@
...
+            | todayMessage     | "Today I'll do this"   |
+        Then  make a GET request to "/standup/search"
+        Then the response status code should be 400
+        And  the response should contains:
+            | statusCode | 400                             |
+            | message    | "Please Provice Search Context" |
+
+
+
+    Scenario: add an empty standup
```
Comment (eddiejaoude) [inline test/features/standup.feature:58]: `standup` here is lowercase and in other places it has a capital. We should try to be consistent. I think having everything lower case in the `Scenario` would make it easier for everyone to be consistent

For example https://github.com/EddieHubCommunity/api/pull/54/files#diff-757cd4aa33cb116bb7e4ebeef9a619042a9b5f4fe6acae2b75bdfbba93b74ca1R45

**Comment by eddiejaoude** [comment]
Looks great 👍 , I left some small comments.

File: test/features/standup.feature (hunk 8 above)
Comment (Cahllagerfeld) [reply test/features/standup.feature:58]: Yes, I definitly see this issue. 
I'll fix this.

**Comment by Cahllagerfeld** [comment]
I hope everything is fine now :D. Now the only thing to fix is the problem with the checks :grimacing:

**Comment by Cahllagerfeld** [comment]
> 
> 
> I hope everything is fine now :D. Now the only thing to fix is the problem with the checks 😬

Hi Eddie, i did some more research on that. Did you do `npm i` or `npm ci` after pull? The difference is, that `npm ci` doesnt write to `package-lock.json`. 
I did `npm i` when I installed the dependencies. This means that I potentially overwrote some entries in the `package-lock.json`. 
You think restoring the lockfile from [this](https://github.com/EddieHubCommunity/api/commit/c22711238127eff1543510f4038fb2a2dd9ba1c5) commit might fix the problem?

**Comment by eddiejaoude** [comment]
> I did npm i when I installed the dependencies. This means that I potentially overwrote some entries in the package-lock.json

I think you should be able to create a new lock file, which should be ok. Let me test locally also

**Comment by eddiejaoude** [comment]
btw I tested it locally and it works fine for me. I think it is still a good idea to generate a new lock file though

I have node `v14.14.0` locally

**Comment by eddiejaoude** [comment]
I will merge this into a temporary branch `issue-11` on the repo, so I can have a play with changes too 🤓 - feel free to create more PR against `issue-11` if you would like to make any changes to this issue also

**Comment by Cahllagerfeld** [comment]
Thats a good idea!

**Comment by eddiejaoude** [comment]
That seems to have fixed it 🎉 #62

**Comment by Cahllagerfeld** [comment]
Thats huge!! :rocket:
Which issues do you see next to be implemented?
I feel quite motivated to grow the api, but I cant really prioritize the open issues and cant decide on which one to work next. Could you help me about that? :sweat_smile:

**Comment by eddiejaoude** [comment]
Your code is now in the `main` branch 🎉 - thank you 🤓 

Wow thank you for your awesome support! Yes the issues are not organised at the moment and that is my fault 🤦‍♂️ 

Could you add a GitHub module, similar to the other modules with tests and swagger etc https://github.com/EddieHubCommunity/api/issues/44

Any questions let us know 🤓

**Comment by Cahllagerfeld** [comment]
Sure :D Then I'll start the Github-Module. I open a new PR then.
